POST http://localhost:4000/api/users/register
Content-Type: application/json

{
  "name": "alaida",
  "email": "alada@allaida.com",
  "password": "123456",
}

### Login
POST http://localhost:4000/api/users/login
Content-Type: application/json

{
  "email": "allida@allida.com",
  "password": "12345"
}

### -------------------------
# 3. Create Content (as user)
@baseUrl = http://localhost:4000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ZGU3NjVmMzEyYjQwNmY2YzJkZjZiNCIsInJvbGUiOiJzdHVkZW50IiwibGV2ZWwiOiIxIiwiaWF0IjoxNzc3NDg1MTY1LCJleHAiOjE3Nzc1NzE1NjV9.NmMqmGCTcFjOd2PnguhyHDyhAd2j3STkKsj3HfWk0Cc
@contentId = 69ebf12f97971102e2711771

### 1. Test backend connection
GET {{baseUrl}}/api/content


### 2. Test top content
GET {{baseUrl}}/api/content/top


### 3. Test one content item by id
GET {{baseUrl}}/api/content/{{contentId}}


### 4. Test trackContentInteraction
POST {{baseUrl}}/api/content/interactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "contentId": "{{contentId}}",
  "interactionType": "like"
}
###